# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBProject',
            fields=[
                ('object_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
